spring:
  mail:
  // host, port는 naver에서 정해준 값
    host: smtp.naver.com 
    port: 465
    // 본인 naver 계정정보 삽입
    username: goott_test@naver.com
    password: mangle*dream
    //전송하기 위한 prop으로 ssl의 신뢰, 권한 등 사용허가
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com